contracts/CMakeLists.txt
Change CON_BASE_URL to a working address https://raw.githubusercontent.com/AntelopeIO/reference-contracts/main/contracts/icons (it was http://127.0.0.1/ricardian_assets/eosio.contracts/icons)
=> [main] change ICON_BASE_URL to a working address

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/rex.cpp
Resolve https://github.com/AntelopeIO/reference-contracts/issues/2
`CDT 3.0.0` introduced nested containers and map handing in ABI generation. It broke reference contracts' ABIs. See description and discussions in https://github.com/AntelopeIO/reference-contracts/issues/2 for details.
This PR replaces the usage of `map` and `deque` with `vector` and produces the same ABIs as prior to `CDT 3.0.0.`
=> Replace usage of deque and map with vector in reference contracts

tests/eosio.limitauth_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_tests.cpp, tests/eosio.token_tests.cpp, tests/eosio.wrap_tests.cpp, tests/main.cpp
This header file is unused and now removed in Leap's `main` branch
=> remove `Runtime.h` include that no longer exists in Leap's libtester

tests/CMakeLists.txt, tests/eosio.powerup_tests.cpp
This PR fixes powerup test compilation issue due to the following change in Leap:
https://github.com/AntelopeIO/leap/commit/18190c138a6cfc33f7f24081cab8c4ff308756b7#diff-6363b75a1986b5ec4c25d00bbeb26d38b264ce1e006b70fd33d85a4a28ca145c
=> Fix for explicit time_point_sec conversion, bump max version to 4.1

contracts/eosio.bios/src/eosio.bios.cpp
Update error messages of `setfinalizer` to match changes made in `leap` PR: https://github.com/AntelopeIO/leap/pull/1989
Resolves #34
=> Update set_finalizer errors

CMakeLists.txt, contracts/CMakeLists.txt, tests/CMakeLists.txt
Bring these two builds knobs over from eos-system-contracts. Needed for building reference-contracts as part of leap's CI so it's not too picky about versions
=> add `SYSTEM_ENABLE_LEAP_VERSION_CHECK` & `SYSTEM_ENABLE_CDT_VERSION_CHECK` build knobs

.cicd/defaults.json, .github/workflows/build.yaml, tests/CMakeLists.txt
After this change only libtester 5.0+ can be used for testing since only leap 5.0 CI creates a ubuntu 22 libtester.
=> update CI to use Ubuntu 22.04 and libtester 5.0 by default, plus update some actions versions

.github/workflows/build.yaml, contracts/eosio.bios/src/eosio.bios.cpp, tests/eosio.bios_inst_fin_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
- Changed tests to use `controller::active_producers()`  instead of accessing `block_header_state` directly.
- Changed to new CDT `finalizer_policy` struct
=> IF: Update for latest IF

tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp
Test coverage for ram action return values
Added test method `convert_json_to_hex` , takes a json and converts it to hex. This is used to generate expected return codes from methods.
Added 6 methods that execute `ram_actions` and take additional arguments with the expected return codes, and ensure expected and actual return codes match. 
- `validate_buyram_return`
- `validate_ramtransfer_return`
- `validate_ramburn_return`
- `validate_buyrambytes_return`
- `validate_sellram_return`
- `validate_buyramself_return`
Resolves #44
=> Test Coverage ram_actions Return Values

CMakeLists.txt
As of libtester 5.0 these aren't needed.
=> rm platform specific openssl

.github/workflows/build.yaml
Enables override of versions during CI builds
May be needed for IF, this matches eos-system-contracts
=> Turn off version checks for leap and cdt

contracts/eosio.system/include/eosio.system/eosio.system.hpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp
For clarity updates to `bytes_sold` and `bytes_purchased` in `ramsell` and `rambuy` functions. Previous more generic `bytes`. Resolves #52
=> updated to bytes_sold and bytes_purchased

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
Merge updated ram_actions and associated tests.
resolves #44
- `ramtransfer`
- `ramburn`
- `buyramself`
- `action_return_sellram`
- `action_return_buyram`
- `action_return_ramtransfer`
- `buyram`
- `buyrambytes`
- `sellram`
- `ramtransfer`
- `ramburn`
- `buyramself`
- `logbuyram`
- `logsellram`
- `logramchange`
=> [Main] Merge ram_actions 

CMakeLists.txt
Bump version in main branch to match next version, `3.4.0-dev`, and to match system contracts 
Fix #54
=> Version bump to 3.4.0-dev

.cicd/defaults.json, tests/eosio.bios_inst_fin_tests.cpp
Leap PR https://github.com/AntelopeIO/leap/pull/2255 changes BLS keys and signatures to base64 url format. Existing tests in BIOS finality use regular base64 format. Update the tests to use base64 URL format.
=> IF: Update BIOS finality tests to use base64url encoded BLS keys and signatures

.cicd/defaults.json
https://github.com/AntelopeIO/reference-contracts/pull/56 changed leap-dev target to `pubkey_base64url` temporarily to get around circular dependency between reference contracts and Leap CICD libtester tests for https://github.com/AntelopeIO/leap/pull/2255. This PR changes it back to `hotstuff_integration`. 
The PR  is created in anticipation of approval of https://github.com/AntelopeIO/leap/pull/2255; it will be merged right after https://github.com/AntelopeIO/leap/pull/2255 is merged, to avoid Leap CICD interruptions on `hotstuff_integration` branch.
=> IF: change leap-dev target back to hotstuff_integration

.cspell/custom-dictionary.txt, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, contracts/eosio.system/src/eosio.system.cpp, contracts/eosio.system/src/producer_pay.cpp, tests/eosio.system_schedules_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
Upgrade related to system vesting
=> Tokenomics - Vesting upgrade

contracts/CMakeLists.txt, contracts/eosio.fees/CMakeLists.txt, contracts/eosio.fees/include/eosio.fees/eosio.fees.hpp, contracts/eosio.fees/src/eosio.fees.cpp, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, contracts/eosio.system/src/eosio.system.cpp, contracts/eosio.system/src/powerup.cpp, contracts/eosio.system/src/producer_pay.cpp, contracts/eosio.system/src/rex.cpp, tests/contracts.hpp.in, tests/eosio.fees_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
- contract deployment optional
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/118
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/121
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/119
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/122
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/123
- https://github.com/eosnetworkfoundation/eos-system-contracts/issues/130
=> Tokenomics - Fees upgrade

contracts/eosio.system/include/eosio.system/eosio.system.hpp
We noticed a docs mismatch that would mislead auditors, integrators, and callers of the `setschedule` method.
This updates the docs to match the new parameters.
=> Fix for setschedule docs

.cicd/defaults.json, tests/eosio.bios_inst_fin_tests.cpp, tests/eosio.limitauth_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
Default libtester changes to run under Savanna. This exposes several test failures. This PR addresses them:
* `eosio_bios_if_tests/set_1_finalizer` failures due to starting from Savanna tester (should have started from Legacy tester)
* `eosio_system_tests/producer_wtmsig and eosio_system_tests/producer_wtmsig_transition` failures due to proposer schedule algorithm change
* `eosio_system_tests/producer_onblock_check` failures due to proposer schedule algorithm change
Resolves
https://github.com/AntelopeIO/reference-contracts/issues/90
https://github.com/AntelopeIO/reference-contracts/issues/92
https://github.com/AntelopeIO/reference-contracts/issues/93
=> Fix test failures under default Savanna libtester

tests/CMakeLists.txt, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
Currently in CICD libtester tests, system_tests takes longest time (about 5 minutes)(https://github.com/AntelopeIO/spring/actions/runs/9468157289/job/26085190747#step:16:984). The next longest test eosio_system_finalizer_key_unit_test is about 1 minute. By splitting it into multiple suites such that each runs about 1 minute in parallel, it will reduce overall libtester running time by 4 minutes.
* Change `tests/CMakeList.txt` to support multiple test suites in a single file
* Split `system_tests` into multiple suites
* Avoid produce unnecesary large number of blocks in eosio.system_tester.hpp
Resolved https://github.com/AntelopeIO/reference-contracts/issues/102
=> Split system tests so that they can run in parallel

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/eosio.system.cpp, contracts/eosio.system/src/rex.cpp, contracts/eosio.system/src/voting.cpp, tests/eosio.system_rex_matured_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
REX upgrades related to buying, selling & unstaking REX.
```c++
/**
* Facilitates the modification of REX maturity buckets
*
* @param num_of_maturity_buckets - used to calculate maturity time of purchase REX tokens from end of the day UTC.
* @param sell_matured_rex - if true, matured REX is sold immediately.
*                           https://github.com/eosnetworkfoundation/eos-system-contracts/issues/134
* @param buy_rex_to_savings - if true, buying REX is moved immediately to REX savings.
*                             https://github.com/eosnetworkfoundation/eos-system-contracts/issues/135
*/
[[eosio::action]]
void rexmaturity(const std::optional<uint32_t> num_of_maturity_buckets, const std::optional<bool> sell_matured_rex, const std::optional<bool> buy_rex_to_savings );
```
```c++ …
```
=> Tokenomics - REX Upgrade

tests/eosio.powerup_tests.cpp
Under Savanna, powerup `weight_tests` fails in both NET and CPU weight_ratio tests:
`tests/eosio.powerup_tests.cpp(410): fatal error: in "eosio_system_powerup_tests/weight_tests": critical check near(get_state().net.weight_ratio, net, 1) has failed`
The root cause is the tests are fragile.
NET and CPU decays are calculated by `update_weight` in the system contract
https://github.com/AntelopeIO/reference-contracts/blob/229dd4f6b358238e34abf9b8ccb26df0b9cbba5c/contracts/eosio.system/src/powerup.cpp#L91-L98
`target_timestamp` is set in tests for example
https://github.com/AntelopeIO/reference-contracts/blob/229dd4f6b358238e34abf9b8ccb26df0b9cbba5c/tests/eosio.powerup_tests.cpp#L382
while `initial_timestamp` is set in contract
https://github.com/AntelopeIO/reference-contracts/blob/229dd4f6b358 …
=> Fix fragile powerup_tests/weight_tests so that they can run under Savanna

tests/eosio.bios_inst_fin_tests.cpp
`instant_finality_extension` renamed to `finality_extension` in https://github.com/AntelopeIO/spring/pull/364
=> instant_finality_extension renamed to finality_extension
